### PR TITLE
Add ca_certs config option for setting custom CA cert path.

### PR DESCRIPTION
**Pull request by xtagon**
This was necessary to solve an issue on a Heroku deploy where the CA default bundle was not being detected automatically.

This option may be useful to others as well.

It would be really helpful if you can merge it in and do a release, so I don't have to specify my fork's URL in my dependencies. Thanks! :-)

### CODE REVIEW

**Comment by xtagon** [comment]
Well, it looks like this didn't fix the problem on Heroku even though my local testing went well. Now I'm waiting on a Heroku ticket before I complete this pull request.

**Comment by xtagon** [comment]
This fix is working for me on Heroku now.

I'm not sure why the CI failed on one of the builds and not the others (I don't understand the error).

**Comment by xtagon** [comment]
Hi @agschwender, are you interested in merging this? I've been using it for a while now and would love to get away from depending on a fork. Does the Travis build error mean anything to you? It makes no sense to me.

Thanks!

**Comment by agschwender** [comment]
Merged in a0d1ec82c4cbfd06dbc1ae046471ad8c7802b2f8

**Pull request closed without merging**
