### PR TITLE
Added preserve_exif option

### PR DESCRIPTION
**Pull request by devoto13**
Here is implementation of functionality described in #36.

The build in Travis fails. That's because I'm working on OS X and expected images was generated with OS X system libraries. I found that after fetching repository I have most of the tests broken, when I run them locally, however in Travis everything is fine. The opposite is also true, when I generate expected images locally it works fine, but fails on Travis.

Could you please generate expected images in proper environment, so it will pass Travis build?

### CODE REVIEW

**Comment by agschwender** [comment]
Looks good. I'll merge it in this weekend.

**Comment by devoto13** [comment]
Great! Thank you.

**Comment by agschwender** [comment]
Sorry for not doing this when I said; was sick last weekend. It's in place now as version 1.1.8. I made one change: renamed the url parameter from `preserve_exif` to `exif`, since I generally opt for shorter url parameters. The config flag still remains `preserve_exif`.

**Comment by devoto13** [comment]
No problems. Hope you're feeling better now! :)

Thanks.

**Comment by agschwender** [comment]
Thank you for the contribution. I think you might be the first contributor that added tests, which is much appreciated.

**Pull request merged**
