### PR TITLE
basic animated gif example

### PR DESCRIPTION
**Pull request by phoet**
@agschwender this is a working prototype for animated gif transformation. all feedback appreciated!

right now the gif is not looping because it somehow looses the proper image headers. i was not able to somehow copy them over.

before: 
```
(Pdb) img.info
{'background': 53, 'extension': ('NETSCAPE2.0', 219), 'version': 'GIF89a', 'transparency': 53, 'duration': 60, 'loop': 0}
```
after:
```
(Pdb) res.info
{'version': 'GIF87a', 'background': 0}
```

### CODE REVIEW

**Comment by agschwender** [comment]
This broke some tests, didn't really dig into it, but looks like it might be because there's till an open file handle. Unless this is more an exercise in just getting it to work and then going back to integrate, would really like to see this integrated more deeply into Pilbox to evaluate the code impact.

**Comment by phoet** [comment]
@agschwender yeah, that would be more interesting to see. i was hoping to get some feedback on handling animated gifs with pillow since i could not make the transformation spit out new gifs that loop properly. looks like this feature was just merged into pillow master. i'll try to get that part working before starting the pilbox integration.

for the tests, it looked like the pictures generated on my mac were not binary compatible to the checked-in expectations. the generated pictures were fully functional and i could not see any differences though.

**Comment by agschwender** [comment]
Yeah, in order for the expected files to match the output generated by Travis, you need to build them on Linux. Pilbox ships with a Vagrantfile which will set that up for you.

**Comment by phoet** [comment]
the gif handling of pillow is not really what i would consider a great api. closing this as i don't see a simple way to integrate it.

**Pull request closed without merging**
