### PR TITLE
Region operation support optional resize

### PR DESCRIPTION
**Pull request by JacopoDaeli**
Since the `region` operation doesn't allow any resize on the cropped region and since concatenate operations are not supported (`region` +`resize`, for example) I added an optional `resize (scale)` when performing a region operation.

The region operation now accepts `w` and `h` as optional parameters, and if at least one of them is stated, `pilbox` will scale the cropped region.

### CODE REVIEW

**Comment by agschwender** [comment]
It's undocumented, but the `op` parameter supports a comma separated list of operations. Haven't looked at your change yet since I'm at work, but it may be achievable via `op=region,resize`

**Comment by JacopoDaeli** [comment]
OK. I will try to use a list of operation.

By the way, try to have a look to my code, since I think my idea is more understandable, and let me know.

**Comment by agschwender** [comment]
What I actually think is preferable about using a list of operations for `op` is that it supports an order of operation. E.g. it can `resize` first, then `region`, or `region`, then `resize`. Or really any permutation of `rotate`, `region`, `resize`. It also is more adaptable: if more operations are added this will continue to work. 

I do agree that if you want to do a `region`, then `resize`, your approach is probably more explicit and easier to understand, but I also think that it complicates the code and adds special cases to accommodate the optional `w` and `h` for `region` operations. I also think the overlap is a little confusing, in that why are there two different ways to do the same thing. Granted, since it's undocumented, it's my own fault for not making this feature more obvious and I can hardly expect you to be aware of it.

**Comment by JacopoDaeli** [comment]
Totally agree. What I can try do to is documenting this feature though :-)

**Pull request closed without merging**
