### PR TITLE
Add `workers` config option to set number of procs

### PR DESCRIPTION
**Pull request by dbader**
Thanks for this awesome project! I'm running Pilbox as the image resizing service for [realpython.com](https://realpython.com) (see https://github.com/realpython/robocrop), deployed on Heroku.

I ran into issues with memory usage because Tornado would decide to spawn 8 worker processes on a low-end Heroku dyno. The sweet spot seems to be at 3 worker processes for this setup.

I made the number of Tornado workers configurable in https://github.com/realpython/robocrop/blob/master/app.py and this fixed our memory usage issues and smoothed out our response time when running Pilbox on Heroku.

This PR ports that functionality back into mainline Pilbox by adding a `workers` config option.

Keep the default of starting one worker per CPU core:

```console
$ python -m pilbox.app
[I 180808 12:47:29 app:353] Starting server...
[I 180808 12:47:29 process:128] Starting 4 processes
```

`--workers N` allows spawning a predefined number of workers:

```console
$ python -m pilbox.app --workers=2
[I 180808 12:47:42 app:353] Starting server...
[I 180808 12:47:42 process:128] Starting 2 processes

$ python -m pilbox.app --workers=8
[I 180808 12:47:58 app:353] Starting server...
[I 180808 12:47:58 process:128] Starting 8 processes
```

Hope this is helpful & please let me know if you need any other changes on the PR in order to move forward 🙂

### CODE REVIEW

**Comment by agschwender** [comment]
A quick look: :+1:. Will take a closer look and merge this weekend.

**Comment by dbader** [comment]
@agschwender Yup no rush, thanks Adam!

**Comment by xtagon** [comment]
Thanks for contributing upstream @dbader, I can use this config option as well 👍

**Comment by agschwender** [comment]
Your change is published in version 1.3.4. Let me know if you have any issues. Thanks for the contribution, much appreciated.

**Comment by dbader** [comment]
Thanks for getting to this so fast, will update/simplify our production setup with the latest Pilbox release now 😄

**Pull request merged**
